homeassistant:

  # Template sensor for the result (platform: template is required)
  template:
  - sensor:
      - name: "Unit Converter Result"
        unique_id: unit_converter_result
        state: "{{ states('sensor.unit_converter_internal') }}"
