homeassistant:

  # Input Number
  input_number:
    convert_value:
      name: "Value to Convert"
      min: 0
      max: 999999
      step: 0.01
      mode: box

  # Input Selects
  input_select:
    convert_from_unit:
      name: "From Unit"
      options:
        - Stopa
        - Inc
        - Yard
        - Milja
        - Nauticka Milja
        - Metar
        - Kilometar
        - Milimetar
        - Centimetar
        - Unca
        - Funta
        - Kilogram
        - Gram
        - Miligram
        - Celzijus
        - Farenhajt

    convert_to_unit:
      name: "To Unit"
      options:
        - Stopa
        - Inc
        - Yard
        - Milja
        - Nauticka Milja
        - Metar
        - Kilometar
        - Milimetar
        - Centimetar
        - Unca
        - Funta
        - Kilogram
        - Gram
        - Miligram
        - Celzijus
        - Farenhajt

  # Template sensor for the result (platform: template is required)
  template:
  - sensor:
      - name: "Unit Converter Result"
        unique_id: unit_converter_result
        state: "{{ states('sensor.unit_converter_internal') }}"
